### ISSUE TITLE
Symmetrical Mod Minor Issues

### ISSUE THREAD

**Issue by ndanyluk** [clee/VoronBFI#20]
Hi Clee, love the BFI parts, already assembled before I saw the symmetrical parts and was going to reprint.  Couple of things I noticed:

* Parts aren't oriented for printing - the housing for example is oriented as they would be assembled on the printer, not face down like the standard BFI parts
* STLs aren't labelled as [a] for accent like the standard BFI parts
* Standard BFI parts use 5x18mm pins with optional BHCS - this mod only supports M3 or M5 BHCS with no option for pins
* Symmetrical Mod isn't listed in the Mods ReadMe with a description like the other mods

Going to see if I can get a PR going with at least the first 2 items updated.  I'll try my hand at the 3rd as well, but my CAD skills are a bit weak in this department

**Comment by orangetruth** [comment]
Also BFI_Front_with_logo_M3_symetrical_x2.stl doesn't actually have a logo
