### ISSUE TITLE
BZI v2.4 Carrier too snug

### ISSUE THREAD

**Issue by Nomsplease** [clee/VoronBFI#28]
The BZI carrier for the Voron 2.4 is too snug on my 9mm idlers that were used in my stock Z idlers. 

These were sourced a long time ago so this may be a non-issue now. My Idlers are 14.06mm wide and the current carrier printed at 14.09mm. They do fit but are way too snug to move. 

I modified the CAD to make one that has a 15mm wide opening for the idler instead of 14mm. The CAD shows the idler is 13mm wide, so I went with 1mm over the size of the idler. I am uploading a ZIP file with the STL and the quickly/crudely done STEP file incase anyone else might need it.

~~I am currently printing this and will validate it works for mine, I will cross this out once I confirm it works for my idlers.~~
They fit just as they should.

[14mm Carrier.zip](https://github.com/clee/VoronBFI/files/14746500/14mm.Carrier.zip)

**Comment by Carl-Wilhelm** [comment]
Thank you. Same problem here with the idlers that came with my LDO kit.

**Comment by clee** [comment]
Did you try the usermod specifically designed for this? https://github.com/clee/VoronBFI/tree/main/usermods/LillianaMirrors/

**Comment by Nomsplease** [comment]
> Did you try the usermod specifically designed for this? https://github.com/clee/VoronBFI/tree/main/usermods/LillianaMirrors/

I didnt see these in the repo at the time. I have been running mine for a while without issue but I dont think we need a duplicate mod here. We can just close this up since it will stay here if its ever needed.
